name: carte_nabil
description: A unified Chat and Membership Scanner App.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Firebase dependencies
  firebase_core: ^2.28.0
  firebase_auth: ^4.17.6
  cloud_firestore: ^4.15.5
  firebase_storage: ^11.6.0
  
  # Scanner dependencies
  camera: ^0.10.5+9
  google_mlkit_text_recognition: ^0.13.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.3

  # Media dependencies
  image_picker: ^1.1.0
  record: ^6.2.0
  audioplayers: ^5.2.1
  video_player: ^2.8.5
  permission_handler: ^11.3.1
  url_launcher: ^6.2.6
  file_picker: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.webp
