name: carte_nabil
description: Specialized Membership Scanner App for ASSIMA-10.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^1.19.0
  
  # Firebase
  firebase_core: ^2.28.0
  cloud_firestore: ^4.15.5
  
  # Scanner
  camera: ^0.10.5+9
  google_mlkit_text_recognition: ^0.13.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.3
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.webp
